CA1_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import homePageView
from posts.views import PostListHome

urlpatterns = [
    path('', PostListHome.as_view(), name='home'),
]

posts/urls.py
from django.urls import path
from .views import (PostListView,
                    PostDetailView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView,
                    PostList,
                    CommentCreateView)

app_name = 'posts'

urlpatterns = [
    path('', PostList.as_view(), name='post_list'),
    path('<uuid:board_id>/', PostList.as_view(), name = 'posts_by_board'),
    path('new/', PostCreateView.as_view(), name='post_new'),
    path('<uuid:board_id>/<uuid:post_id>/', PostDetailView.as_view(), name='post_detail'),
    path('<uuid:pk>/edit/', PostUpdateView.as_view(), name='post_update'),
    path('<uuid:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('<uuid:board_id>/<uuid:post_id>/comment_new', CommentCreateView.as_view(), name='comment_new')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

{% if user.is_authenticated %}

<nav class="navbar navbar-dark navbar-expand-sm bg-dark">
    <text class="dropdown navbar-brand">
        <a class="dropdown-toggle nav-link text-light" href="#" id="navbardrop"
                data-toggle="dropdown">{{user.username}}</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'show_profile' user.profile.pk %}">Profile</a>
            <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
            <a class="dropdown-item" href="{% url 'logout' %}">Sign Out</a>
        </div>
    </text>
    <ul class="navbar-nav ml-auto card">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbardrop" data-toggle="dropdown">
                Boards
            </a>
            <div class="dropdown-menu">
                {% for board in links %}
                <a class="dropdown-item" href="{{board.get_absolute_url}}">{{board.name}}</a>
                {% endfor %}
            </div>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto card">
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'posts:post_new' %}">Create Post</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'posts:post_list' %}">All Posts</a>
        </li>
    </ul>
</nav>

{% else %}

<nav class="navbar navbar-dark navbar-expand-sm bg-dark">
    <text class="dropdown navbar-brand">
        <a class="dropdown-toggle nav-link text-light" href="#" id="navbardrop"
                data-toggle="dropdown">You are not logged in.</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'login' %}">Log In</a>
            <a class="dropdown-item" href="{% url 'signup' %}">Sign Up</a>
        </div>
    </text>
    <ul class="navbar-nav ml-auto card">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbardrop" data-toggle="dropdown">
                Boards
            </a>
            <div class="dropdown-menu">
                {% for board in links %}
                <a class="dropdown-item" href="{{board.get_absolute_url}}">{{board.name}}</a>
                {% endfor %}
            </div>
        </li>
    </ul>
        <ul class="navbar-nav ml-auto card">
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'posts:post_list' %}">All Posts</a>
            </li>
        </ul>
</nav>

{% endif %}
<br>

<body>
    {% block content %}
    {% endblock content %}
</body>

</html>

templates/comment_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row w-100">
    <div class="col-4"></div>
    <div class="container-sm p-3 bg-dark col-4">
        <form method="post" id="loginForm" class="text-light" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>Create Comment</h1>
            {{ form|crispy }}
            <br>
            <button type="submit" value="Submit">Submit</button>
        </form>
    </div>
    <div class="col-4"></div>
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
<header>
    <title>Home</title>
</header>
<div class="container-fluid text-white">
    <div class="card bg-dark p-3 m-3">
        {% if user.is_authenticated %}
            <h1 class="card-title">Welcome, {{ user.username }}.</h1>
        {% else %}
            <h1 class="card-title">Welcome.</h1>
        {% endif %}
        <p>These are the 3 latest posts;</p>
        <div class="container-fluid">
            <div class="rounded card-columns bg-dark m-3 p-3">
                {% for post in object_list|slice:"::-1"|slice:":3" %}
                <div class="card shadow bg-light p-2">
                    <div class="card shadow">
                        <div class="card-title text-center">
                            <h1><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
                            <text class="text-dark">by <a class="" href="{% url 'show_profile' pk=post.author.pk %}">{{ post.author }}</a> in {{ post.board }}</text>
                        </div>
                    </div>
                    <div class="float-left">
                        <img class="shadow img-thumbnail m-2 post-list-img" src="{{ post.image.url }}"
                        alt="{{ post.title }}">
                    </div>
                    <p class="card-text text-dark">{{ post.body|truncatechars:300 }}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>

<body>
    {% block content %}
    <div id="loginContainer">
        <form method="post" id="loginForm">
            {% csrf_token %}
            <h1>
                Login
            </h1>
            <input type="text" id="username" placeholder="Username" required><br><br>
            <input type="password" id="password" placeholder="Password" required><br><br>
            <button type="submit">Login</button>
        </form>
    </div>
    {% endblock content %}
</body>
</html>

templates/post_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row w-100">
    <div class="col-4"></div>
    <div class="container-sm p-3 bg-dark col-4">
        <form method="post" id="loginForm" class="text-light">
            {% csrf_token %}
            <h1>Delete</h1>
            <p>Are you sure you want to delete "{{ post.title }}"?</p>
            <button class="btn btn-danger ml-2" type="submit">Confirm</button>
        </form>
    </div>
    <div class="col-4"></div>
</div>
{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %}
<header>
   <title>{{ post.title }}</title>
</header>

{% block content %}
<h5><a class="ml-3" href="{% url 'posts:post_list' %}">
      <- Back</a>
</h5>
<div class="row w-100">
   <div class="container ml-3 col-7">
      <div class="card d-flex flex-nowrap bg-dark rounded p-3">
         <div class="shadow w-100 bg-light d-inline-block">
            <div class="card shadow m-1">
               <h1 class="card-title text-center">{{ post.title }}</h1>
            </div>
            <div class="float-left">
               <img class="shadow m-2 img-thumbnail original-post-image" src="{{ post.image.url }}"
                  alt="{{ post.title }}">
            </div>
            <p class="card-text"><a href="{% url 'show_profile' pk=post.author.pk %}">{{ post.author }}</a>: {{post.body }}</p>
         </div>
         {% if user.pk == post.author.pk %}
         <div class="card-footer bg-dark p-0">
            <p class="mt-2 mb-0"><a href="{% url 'posts:post_delete' pk=post.id %}">Delete Post</a> | <a href="{% url 'posts:post_update' pk=post.id %}">Edit Post</a> | 
         {% endif %}
         <a href="{% url 'posts:comment_new' post.board_id post.id %}">New Comment</a></p>
         </div>
         <div class="col-5 m-0"></div>
      </div>
      <div class="mb-3"></div>
      <!--For Comments-->
</div>
<div class="w-100 row mt-3">
      {% for comment in post.comments.all %}
      <div class="container ml-5 col-7">
         <div class="card d-flex flex-nowrap bg-dark rounded p-3 mb-1">
            <div class="shadow w-100 bg-light d-inline-block">
               {% if comment.has_image %}
                  <div class="float-left">
                     <img class="shadow m-2 img-thumbnail original-post-image" src="{{ comment.image.url }}"
                        alt="{{ comment.author }}'s Image">
                  </div>
                  <p class="card-text p-2"><a href="{% url 'show_profile' pk=comment.author.pk %}">{{ comment.author.username }}</a>: {{ comment.comment }}</p>
               {% else %}
                  <p class="card-text p-3"><a href="{% url 'show_profile' pk=comment.author.pk %}">{{ comment.author.username }}</a>: {{ comment.comment }}</p>
               {% endif %}
            </div>
         </div>
      </div>
   
      {% endfor %}
   </div>
   <div class="col-5"></div>
</div>


{% endblock content %}

templates/post_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row w-100">
    <div class="col-4"></div>
    <div class="container-sm p-3 bg-dark col-4">
        <form method="post" id="loginForm" class="text-light">
            {% csrf_token %}
            <h1>Edit</h1>
            {{ form|crispy }}
            <br>
            <button type="submit" value="Submit">Submit</button>
        </form>
    </div>
    <div class="col-4"></div>
</div>
{% endblock content %}

templates/post_list.html
{% extends 'base.html' %}

{% block content %}
{% if board.name != None %}
<h1 class="text-center">- {{ board.name }} -</h1>
{% else %}
<h1 class="text-center">- All -</h1>
{% endif %}
<div class="container-fluid">
    <div class="rounded card-columns bg-dark m-3 p-3">
        {% for post in posts %}
        <div class="card shadow bg-light p-2">
            <div class="card shadow">
                <div class="card-title text-center">
                    <h1><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
                    <text class="text-dark">by <a class="" href="{% url 'show_profile' pk=post.author.pk %}">{{ post.author }}</a> in {{ post.board }}</text>
                </div>
            </div>
            <div class="float-left">
                <img class="shadow img-thumbnail m-2 post-list-img" src="{{ post.image.url }}"
                alt="{{ post.title }}">
            </div>
            <p class="card-text">{{ post.body|truncatechars:300 }}</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/post_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-4"></div>
    <div class="container-sm p-3 bg-dark col-4">
        <form method="post" id="loginForm" class="text-light">
            {% csrf_token %}
            <h1>Create Post</h1>
            {{ form|crispy }}
            <button type="submit" value="Submit">Submit</button>
        </form>
    </div>
    <div class="col-4"></div>
</div>
{% endblock content %}